DROP SCHEMA IF EXISTS __APP__ CASCADE;
DROP ROLE IF EXISTS __APP__;

CREATE ROLE __APP__ LOGIN PASSWORD '__APP___pass';
CREATE SCHEMA __APP__ AUTHORIZATION __APP__;

REVOKE ALL ON SCHEMA __APP__ FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA __APP__ TO __APP__;
GRANT USAGE, CREATE ON SCHEMA __APP__ TO postgres;

ALTER DEFAULT PRIVILEGES IN SCHEMA __APP__
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO __APP__;
ALTER DEFAULT PRIVILEGES IN SCHEMA __APP__
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO postgres;
